# Postgresql
#   Ensure the pg gem is defined in your Gemfile
#   gem 'pg'
#


#POSTGRES local (cloud9)
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 50
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
development:
  <<: *default
  database: ff_orders_dev
test:
  <<: *default
  database: ff_orders_test

production:
#  <<: *default
  host: localhost
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>


 
# #POSTGRES from webserver
# default: &default
# adapter: postgresql
# encoding: unicode
# pool: 50
# webaddress: 'brapp.avifoodsystems.com'
# host: 'PG-SQL-SVR-1'
# port: 5432
# database: 'BRWeb'
# username: 'rgrayson'
# password: '$4Z39VeE#BG8+LFd6TNw'

# development:
#   <<: *default
  
# test:
#   <<: *default
  
# production:
#   <<: *default
  