# Postgresql
#   Ensure the pg gem is defined in your Gemfile
#   gem 'pg'
#

# original
# default: &default
#   adapter: sqlite3
#   pool: 5
#   timeout: 5000
# development:
#   <<: *default
#   database: db/development.sqlite3
# test:
#   <<: *default
#   database: db/test.sqlite3
# production:
#   <<: *default
#   database: db/production.sqlite3


#POSTGRES
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 50
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
development:
  <<: *default
  database: ff_orders_dev
test:
  <<: *default
  database: ff_orders_test
production:
  <<: *default
  host: localhost
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

# webserver, this does not work
# adapter: postgresql
# encoding: unicode
# pool: 50
# webaddress: 'brapp.avifoodsystems.com'
# host: 'pg-sql-svr-1'
# port: 5432
# database: 'BRWeb'
# username: 'rgrayson'
# password: ''